Qg 1/implement login
d-r-q/QYoga pull request #15
Opened 2023-03-01 19:45 UTC by nntrifonova

## Чеклист

* Пулл-реквест
  * [+] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [*] Я убедился, что все проверки пршли успешно
  * [+] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [+] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [+] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [-] Я видел, как каждый тест превратился из красного в зелёный

2023-03-02 06:09 UTC, d-r-q requested changes

2023-03-02 06:09 UTC, d-r-q commented on build/bootJarMainClassName
> +nsu.fit.qyoga.app.QYogaApplicationKt
Директория build и всё её содержимое не должно быть в гите. Это надо удалить из ПРа

2023-03-02 06:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/WebSecurityConfig.kt
> +                    .antMatchers(HttpMethod.GET, "/second").hasAuthority(Role.ROLE_ADMIN.toString())
а /second точно надо в финальной версии?

2023-03-02 06:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +) : UserDetails {
Почему это всё наллбл?

2023-03-02 06:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +        fun build(user: User?): UserDetailsImpl {
И это наллабл?

2023-03-02 06:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +                ?.collect(Collectors.toList())!!
И ты тут же ни с того ни, сего выбрасываешь NPE, если вдруг null.
Судя по всему, тебе в этом файле надо удалить все ? и !!

2023-03-02 06:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +                ?.collect(Collectors.toList())!!
До !! я вообще всегда буду докапываться и вставляя это тебе надо иметь железобетонные аргументы, что тут никогда не вылетит NPE и что без !! обойтись невозможно/нецелесообразно

2023-03-02 06:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsServiceImpl.kt
> +    override fun loadUserByUsername(username: String): UserDetails {
Это надо делать через параметр конструктора:

```kotlin
class UserDetailsServiceImpl(private  val usersRepo: UsersRepo)
```

2023-03-02 06:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsServiceImpl.kt
> +    override fun loadUserByUsername(username: String): UserDetails {
lateinit - то же что и !!. Всегда буду докапываться и всегда надо иметь железобетонный аргумент, что подругому никак

2023-03-02 06:09 UTC, d-r-q commented on src/main/resources/static/css/auth.css
> +a {
То же что и у Маши - возьми ту же тему бутстрапа

2023-03-02 06:09 UTC, d-r-q commented on src/main/resources/application.yaml
> +    web: error
Почему error? инфо часто полезен при отладке

2023-03-02 06:09 UTC, d-r-q commented on build.gradle.kts
> +
Это зачем? Ты собралась писать полноценные UI-тесты?

2023-03-02 16:33 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +                ?.collect(Collectors.toList())!!
Отвечу про все ? и !! здесь. 
функция findByUsername в UserRepo возвращает user?, и ее я вызываю, чтобы создать юзера в UserDetailsServiceImpl, и из-за этого там дальше всюду пришлось все сделать с ?, и как это сделать без них не нашла

2023-03-02 16:35 UTC, nntrifonova commented on src/main/resources/application.yaml
> +    web: error
поменяла

2023-03-02 16:40 UTC, nntrifonova commented on build.gradle.kts
> +
не совсем поняла сначала, что значило внешние тесты, и поэтому предположила, что ui тоже надо тестировать.
уберу эти зависимости.

2023-03-02 16:44 UTC, nntrifonova commented on build.gradle.kts
> +
Также хотела уточнить на тему тестов. На странице авторизации получается что достаточно внешних тестов, или внутренние тоже нужно дописать? Просто пока что никаких новых данных и переходов от логина вроде не происходит

2023-03-02 16:47 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/WebSecurityConfig.kt
> +                    .antMatchers(HttpMethod.GET, "/second").hasAuthority(Role.ROLE_ADMIN.toString())
оно лишнее. убрала.

2023-03-02 16:50 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsServiceImpl.kt
> +    override fun loadUserByUsername(username: String): UserDetails {
изменила на параметр конструктора

2023-03-02 16:53 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +                ?.collect(Collectors.toList())!!
fun findByUsername(username: String): User?

2023-03-04 01:41 UTC, d-r-q commented on build/bootJarMainClassName
> +nsu.fit.qyoga.app.QYogaApplicationKt
![image](https://user-images.githubusercontent.com/1336130/222868917-4a9295f4-3eb7-4735-be3d-80a43552d620.png)

2023-03-04 01:42 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +) : UserDetails {
![image](https://user-images.githubusercontent.com/1336130/222868973-7ebb3f5a-7250-4650-8d75-074081d89d06.png)

2023-03-04 01:44 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +                ?.collect(Collectors.toList())!!
Функция-то возвращает User?, но ты ты дашье делашеь ?: и тебя val user уже User

2023-03-04 01:45 UTC, d-r-q commented on src/main/resources/static/css/auth.css
> +a {
![image](https://user-images.githubusercontent.com/1336130/222869139-93113964-ad27-4097-810d-5fdd442bea68.png)

2023-03-04 01:47 UTC, d-r-q commented on build.gradle.kts
> +
По тестам - обязательно должны быть внешние тесты. Внутренние пишутся только на сложную логику

2023-03-04 06:36 UTC, nntrifonova commented on build/bootJarMainClassName
> +nsu.fit.qyoga.app.QYogaApplicationKt
поправила

2023-03-04 06:36 UTC, nntrifonova commented on src/main/resources/static/css/auth.css
> +a {
изменила

2023-03-04 07:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +) : UserDetails {
исправила

2023-03-04 07:32 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +        fun build(user: User?): UserDetailsImpl {
исправила

2023-03-04 07:32 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/users/internal/UserDetailsImpl.kt
> +                ?.collect(Collectors.toList())!!
все поменяла

2023-03-08 11:24 UTC, d-r-q approved these changes

2023-03-08 11:24 UTC, merged