13 implement questionnaires list
d-r-q/QYoga pull request #16
Opened 2023-03-07 13:07 UTC by Zertalian1

## Чеклист

* Пулл-реквест
  * [ ] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [ ] Я убедился, что все проверки пршли успешно
  * [ ] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [ ] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [ ] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [ ] Я видел, как каждый тест превратился из красного в зелёный

2023-03-08 08:36 UTC, d-r-q requested changes

2023-03-08 08:36 UTC, d-r-q commented on build/kotlin/QYoga001SNAPSHOTplainjar-classes.txt
> +C:\Users\zerta\IdeaProjects\QYoga\build\classes\kotlin\main\nsu\fit\platform\errors\DomainException.class;C:\Users\zerta\IdeaProjects\QYoga\build\classes\kotlin\main\nsu\fit\platform\errors\ResourceN
build надо удалить

2023-03-08 08:36 UTC, d-r-q commented on build/kover/errors/test.log
> +[2023.03.07 20:17:38] (Coverage): Error during class instrumentation: org.springframework.boot.logging.log4j2.Log4J2LoggingSystem
Сборка не проходит

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +    override fun findQuestionnaires(title: String?, page: Page): List<QuestionnaireDto> {
Нафига тебе кастоманая страница? чем спринговые неканают?

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        val pageable: PageRequest = if (page.orderType == OrderType.DESK) {
В иф надо пихать минимум кода

```kotlin
val sort = if (page.orderType. == OrderType.DESK) Sort.by("title").descending() else Sort.by("title")
val pageRequest = PageRequest.of(page.pageNum - 1, Page.pageSize, sort)
```

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +
Не надо заменять ифы на леты. Ветки ифов не должны содержать дублирования кода

```kotlin
        val entities = if (title == null) {
            questionnaireRepo.findAll(pageable)
        } else {
            questionnaireRepo.findAllByTitleContaining(title, pageable)
        }
        return entities.map { QuestionnaireDto(id = it.id, title = it.title) }.toList()
```

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        return title?.let {
Тош самое. if (title != null) намного проще распарсить в голове чем, title?.let

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +class QuestionnaireServiceImpl(
Мысль вслух - если ты на пару тривиальных запросов к тривиальной потратил 9 дней, то у меня большие сомнения, что ты осилишь сделать создание опросов за 11 дней

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/ports/QuestionnairesController.kt
> +    fun getQuestionnairesList(model: Model): String {
Этот метод взрывается:

```
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "(exercises.getPageable().pageNumber == 0) ? 'disabled' : ''" (template: "questionnaire/questionnaire-list" - line 81, col 41)
at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292)
```

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/ports/QuestionnairesController.kt
> +
Должна быть возможность одновременно и отфильтровать и отсортировать

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/ports/QuestionnairesController.kt
> +    @PostMapping("/sort")
Это всё должно быть гетом

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/ports/QuestionnairesController.kt
> +    @PostMapping("/search")
И это тоже гетом

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/ports/QuestionnairesController.kt
> +            questionnaireService.findQuestionnaires(searchDto.title, Page(orderType = searchDto.page.orderType))
Опросы и их кол-во надо передавать параметрами

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/utils/OrderType.kt
> +enum class OrderType(val type: String) {
Зачем это?

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/utils/OrderType.kt
> +    ASK("ASK"),
Ещё и с опечаткой - ascending

2023-03-08 08:36 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/utils/Page.kt
> +data class Page(
Надо использовать спринговые классы

2023-03-08 08:36 UTC, d-r-q commented on src/main/resources/templates/questionnaire/questionnaire-list.html
> +<header th:insert="fragments/headerNavPanel :: headerNavPanel" ></header>
Это уже шаг в правильную сторону, но надо ещё дальше - для страницы прилоежния надо завести один файл, который будет включать общие заголовок, навигацию и футер и параметризованное тело.
Вот чёт в этом районе вроде должно быть: https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#parameterizable-fragment-signatures

2023-03-08 08:36 UTC, d-r-q commented on src/main/resources/templates/questionnaire/questionnaire-list.html
> +                                <input aria-describedby="basic-addon2"
Поиск вообще работает?

2023-03-08 08:36 UTC, d-r-q commented on src/main/resources/templates/questionnaire/questionnaire-list.html
> +                                           hx-select="#exercises-list"
Ты тут тоже качаешь всю страницу целиком и выдираешь из неё только данные? Давай тоже качать только то, что надо

2023-03-08 08:36 UTC, d-r-q commented on src/main/resources/static.url
> +URL=https://github.com/d-r-q/QYoga/tree/qg-7/implement-api-for-the-exercise-module/src/main/resources/static
Эт чёт очень странное. Что это?

2023-03-08 08:36 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/external/QuestionnairesTest.kt
> +class QuestionnairesTest : QYogaAppTestBase()
Это зачем?

2023-03-08 08:36 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/internal/QuestionnairesServiceTests.kt
> +        questionnairesASK.size shouldBe 10
Эм, а где проверка, что оно хоть как-то отсортировано?

2023-03-08 08:36 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/internal/QuestionnairesServiceTests.kt
> +        questionnaires.size shouldBe 10
А где проверка, что это не список из 10 null-ов? 10 объектов с наллами в тайтлах?

2023-03-08 08:36 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/internal/QuestionnairesServiceTests.kt
> +        val questionnairesPage2 = questionnaireService.findQuestionnaires(null, Page(pageNum = 2))
Тут ещё надо проверить, что нет пересечения и дырок

2023-03-08 08:36 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/internal/QuestionnairesServiceTests.kt
> +        questionnaires.size shouldBe 6
Где проверка что у них тайтл соответсвует запросу?

2023-03-08 08:36 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/ui/QuestionnairesViewTest.kt
> +                node("#questionnaire-list") { exists() }
Тут ещё надо проверить что есть хотя бы одна строка и там данные ожидаемой формы - числа, где числа, не пустая строка где не пусая строка, даты в нужном формате, где даты

2023-03-13 13:11 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +    override fun findQuestionnaires(title: String?, page: Page): List<QuestionnaireDto> {
заменил на спринговые

2023-03-13 13:13 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        val pageable: PageRequest = if (page.orderType == OrderType.DESK) {
Исправил

2023-03-13 13:13 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +
Исправил

2023-03-14 02:10 UTC, closed without merging