Qg 13 implement questionnaires list
d-r-q/QYoga pull request #21
Opened 2023-03-15 02:16 UTC by Zertalian1

## Чеклист

* Пулл-реквест
  * [ ] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [ ] Я убедился, что все проверки пршли успешно
  * [ ] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [ ] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [ ] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [ ] Я видел, как каждый тест превратился из красного в зелёный

2023-03-16 03:39 UTC, d-r-q requested changes

2023-03-16 03:39 UTC, d-r-q commented on build/classes/kotlin/main/nsu/fit/qyoga/app/WebSecurityConfig.class
build всё ещё надо убрать...

2023-03-16 03:39 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        val entities = if (title == null) {
В продолжение [этой](https://github.com/d-r-q/QYoga/pull/16#discussion_r1133921615) дискусси.

Ты разные части одного и того же кода фактически растащил по разным местам. Ещё и условие там обернул.

Надо сделать так:
```kotlin
        val page = if (title == null) {
            questionnaireRepo.findAll(PageRequest.of(0 или 1, Int.MAX_VALUE))
        } else {
            val entities = questionnaireRepo.findAllByTitleContaining(title, pageRequest)
            val count = questionnaireRepo.countAllByTitleContaining(title)
            PageImpl(entities, pageRequest, count)
        }
        return page.map { QuestionnaireDto(id = it.id, title = it.title) }
```

А следующим шагом надо формирование страницы инкапслуировать в экстеншн функцию репоза:
```kotlin
interface QuestionnaireRepo { ... }

fun QuestionnaireRepo.findPageByTitle(title: String, pageRequest: PageRequest): Page<Questionnaire> = ...
```

И тогда в сервисе у тебя останется:
```kotlin
            val page = if (title == null) {
            questionnaireRepo.findAll(PageRequest.of(0 или 1, Int.MAX_VALUE))
        } else {
            questionnaireRepo.findPageByTitle(title, PageRequest.of(0 или 1, Int.MAX_VALUE))
        }
        return page.map { QuestionnaireDto(id = it.id, title = it.title) }
```

2023-03-16 03:39 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnairesController.kt
> +    fun sortQuestionnaires(
В продолжение [этой](https://github.com/d-r-q/QYoga/pull/16#discussion_r1129085691) дискуссии. Я всё ещё не понимаю зачем два метода

2023-03-16 03:39 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        val sort = if (questionnaireSearchDto.orderType == "DESK") {
В продолжение [этой](https://github.com/d-r-q/QYoga/pull/16#discussion_r1129086899) дискуссии. Теперь у тебя опечатка в DESK

2023-03-16 05:16 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnairesController.kt
> +    fun sortQuestionnaires(
удалил лишний эндпоинт

2023-03-16 05:16 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        val sort = if (questionnaireSearchDto.orderType == "DESK") {
да, правильно DESC ...

2023-03-16 08:09 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        val entities = if (title == null) {
Поправил

2023-03-17 01:15 UTC, d-r-q requested changes

2023-03-17 01:15 UTC, d-r-q commented on src/main/resources/templates/fragments/headerNavPanel.html
> +<div th:fragment="headerNavPanel">
Переведи на эти фрагменты страницы Маши и Нади, пожалуйста

2023-03-17 01:15 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/QuestionnaireServiceImpl.kt
> +        val entities = if (title == null) {
Теперь вроде осталось удалить ток getQuestionnairesCount, который используется только в тестах

2023-03-17 01:15 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnairesController.kt
> +        @RequestParam(value = "pageNumber", required = false, defaultValue = "0") pageNumber: Int,
QuestionnairesController

Это надо обернуть в Pageable и сортировку брать оттуда же (выкосить её из QuestionnaireSearchDto). Но саму QuestionnaireSearchDto оставить - может ещё пригодится.

https://www.baeldung.com/spring-data-web-support#1-using-pageable-as-a-controller-method-parameter

2023-03-17 14:29 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnairesController.kt
> +        @RequestParam(value = "pageNumber", required = false, defaultValue = "0") pageNumber: Int,
Дело сделано

2023-03-17 14:31 UTC, Zertalian1 commented on src/main/resources/templates/fragments/headerNavPanel.html
> +<div th:fragment="headerNavPanel">
Сделал

2023-03-18 11:21 UTC, merged