Qg 14/implement clients list
d-r-q/QYoga pull request #22
Opened 2023-04-03 11:13 UTC by nntrifonova

## Чеклист

* Пулл-реквест
  * [+] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [+] Я убедился, что все проверки пршли успешно
  * [+] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [+] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [+] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [+] Я видел, как каждый тест превратился из красного в зелёный

2023-04-04 03:50 UTC, d-r-q requested changes

2023-04-04 03:50 UTC, d-r-q commented on .github/workflows/build-docker-image.yaml
> +name: build-docker-image
Это же вроде мой файл и он уже есть в мастере - зачем он здесь?

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    @PostMapping("/error-p")
Тут точно POST обязателен?

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    private val userRepo: UsersRepo
Контроллеры не могут использовать репозы напрямую - надо сервис заинжектить

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnairesController.kt
> +class QuestionnairesController(
Это тоже вроде уже в мастере, тебе, похоже надо на мастер ребейзнуться

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        if (clientService.deleteClient(id)) {
Зачем этот иф?

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +    @PostMapping("/delete/{id}")
Это надо сделать DELETE-ом

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/QYogaApplication.kt
> +@ComponentScan("nsu.fit.qyoga.core.clients")
Это зачем? На крайнях их надо унести в соответствующие конфиги и там уже пакет не нужен будет

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/WebSecurityConfig.kt
> +            .defaultSuccessUrl("/clients")
У меня идёт редирект на http://localhost:8080/?continue и там ошибка

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Dto/ClientListDto.kt
> +data class ClientListDto(
Это же не лист, а отдельный клиент

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Dto/ClientListSearchDto.kt
> +data class ClientListSearchDto(
И тут не список

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Client.kt
> +data class Client(
Этот класс вроде не используется

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Client.kt
> +    val email: Email,
Email - аннотация, если класс начать использовать - сомневаюсь, что он будет работать

2023-04-04 03:50 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/ClientConfig.kt
> +@EnableJdbcRepositories
У тебя тут вроде больше не использюутся репозы - надо удалить

2023-04-04 03:50 UTC, d-r-q commented on src/main/resources/templates/clients-list.html
> +        window.addEventListener('DOMContentLoaded', event => {
Это же у тебя вроде уже есть в js/script.js - его и надо импортнуть

2023-04-04 03:50 UTC, d-r-q commented on src/main/resources/templates/clients-list.html
> +<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
Это надо взять из фрагментов, как в questionnaire-list

2023-04-04 03:50 UTC, d-r-q commented on src/main/resources/templates/clients-list.html
> +<head>
А заголовок надо попытаться вытащить в параметризованный фрагмент и заиспользовать его во всех страницах.

https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#parameterizable-fragment-signatures

2023-04-04 03:50 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/infra/QYogaAppTestBase.kt
> +    fun GetAuthCookie(): Cookie {
Пробел и getAuthCookie

2023-04-04 03:50 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +        header("Location", StringEndsWith.endsWith("1"))
Это ничего и ни как не проверяет - надо удалить

2023-04-04 03:50 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +        val clients = clientService.getClients(
Это часть When

2023-04-04 03:50 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +        header("Location", StringEndsWith.endsWith("clients"))
Это ничего и ни как не проверят - надо удалить.
Сервисы ничего не знают ни про http, ни про заголовки, ни про Location

2023-04-04 03:50 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/ui/ClientListViewTest.kt
> +                node("td") { exists() }
Надо ещё проверить что в первой строке в каждой колонке содержится разумное значение

2023-04-04 03:50 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/ui/ClientListViewTest.kt
> +            }
Тут, наверное, надо ещё проверить, что в полях ввода сохранились изначальные значения?

2023-04-05 17:02 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +    @PostMapping("/delete/{id}")
Меняю на delete и метод удаления в htmx ловлю ошибку 405 при нажатии на кнопку, уже второй день не понимаю как это побороть и почему оно возникает.

2023-04-05 17:06 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnairesController.kt
> +class QuestionnairesController(
Не знаю как это сюда залезло, я это и не добавляла вручную. Возможно ребейс как-то криво сделала сначала, но у меня щас актуальный мастер

2023-04-05 17:06 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        if (clientService.deleteClient(id)) {
убрала

2023-04-05 17:06 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Dto/ClientListDto.kt
> +data class ClientListDto(
переименовала

2023-04-05 17:07 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Dto/ClientListSearchDto.kt
> +data class ClientListSearchDto(
переименовала

2023-04-05 17:07 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Client.kt
> +    val email: Email,
заменила

2023-04-05 17:07 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/ClientConfig.kt
> +@EnableJdbcRepositories
удалила

2023-04-05 17:07 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/infra/QYogaAppTestBase.kt
> +    fun GetAuthCookie(): Cookie {
переименовала

2023-04-05 17:08 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +        header("Location", StringEndsWith.endsWith("1"))
удалила

2023-04-05 17:08 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +        header("Location", StringEndsWith.endsWith("clients"))
удалила

2023-04-05 17:14 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +        val clients = clientService.getClients(
не совсем поняла замечание

2023-04-05 17:18 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/WebSecurityConfig.kt
> +            .defaultSuccessUrl("/clients")
это потому что пермишены меняла, и поставила вместо пермит ол, роль терапевта и роль админа, но так не дает сразу двум ролям разрешить. Пока вернула permitAll

2023-04-05 17:25 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Client.kt
> +data class Client(
Да, просто побоялась его удалять, тк может в дальнейшем понадобиться

2023-04-06 13:59 UTC, nntrifonova commented on src/main/resources/templates/clients-list.html
> +        window.addEventListener('DOMContentLoaded', event => {
импортнула

2023-04-06 13:59 UTC, nntrifonova commented on src/main/resources/templates/clients-list.html
> +<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
заменила

2023-04-06 14:00 UTC, nntrifonova commented on src/main/resources/templates/clients-list.html
> +<head>
вытащила <head> в отдельный заголовок

2023-04-06 14:28 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +    @PostMapping("/delete/{id}")
я справилась

2023-04-06 16:27 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    private val userRepo: UsersRepo
сделала

2023-04-06 16:48 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/ui/ClientListViewTest.kt
> +            }
Так тут же не присходит ввод для поиска. Или проверить плейсхолдеры "Имя" и тд. сами по себе?

2023-04-06 16:50 UTC, nntrifonova commented on .github/workflows/build-docker-image.yaml
> +name: build-docker-image
Возможно я как-то неправильно ребейснулась, но сама я это не добавляла

2023-04-06 16:56 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    @PostMapping("/error-p")
На этот адрес будет идти редирект при ошибке, и если она происходит, то POST будет сообщение о неверном вводе выдавать. Не придумала как без него обойтись

2023-04-07 12:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/QYogaApplication.kt
> +@ComponentScan("nsu.fit.qyoga.core.clients")
Исправила

2023-04-09 02:01 UTC, d-r-q commented on .github/workflows/build-docker-image.yaml
> +name: build-docker-image
Ну видимо да, как минимум этого всего не должно быть в твоей ветке:

![image](https://user-images.githubusercontent.com/1336130/230750392-94ca342a-c2e6-4cc1-9316-6ff49efce868.png)

Попробуй сделать интерактивный ребейз своей ветки на мастер, и выкинуть при этом все левые коммиты

2023-04-09 02:13 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    @PostMapping("/error-p")
jr

2023-04-09 03:09 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    private val userRepo: UsersRepo
findByUsernameServ - Serv - это что значит?

2023-04-09 03:13 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +        val clients = clientService.getClients(
ммм, ну вообще я опечатался - имел ввиду Then. Но даже это делать не надо

2023-04-09 03:44 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/ui/ClientListViewTest.kt
> +            }
Да, ок

2023-04-09 17:17 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    private val userRepo: UsersRepo
исправила

2023-04-11 02:05 UTC, closed without merging