Qg 14/implement clients list rebased
d-r-q/QYoga pull request #23
Opened 2023-04-10 03:00 UTC by nntrifonova

## Чеклист

* Пулл-реквест
  * [+] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [+] Я убедился, что все проверки пршли успешно
  * [+] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [+] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [+] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [+] Я видел, как каждый тест превратился из красного в зелёный

2023-04-11 04:51 UTC, d-r-q requested changes

2023-04-11 04:51 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/WebSecurityConfig.kt
> +            .defaultSuccessUrl("/clients")
В продолжении [этой](https://github.com/d-r-q/QYoga/pull/22#discussion_r1156692195) дискуссии.

> поставила вместо пермит ол, роль терапевта и роль админа, но так не дает сразу двум ролям разрешить.

`hasAnyAuthority` должно сработать

2023-04-11 04:51 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/ClientConfig.kt
> +@ComponentScan("nsu.fit.qyoga.core.clients")
В продолжение [этой](https://github.com/d-r-q/QYoga/pull/22#discussion_r1156692053) дискуссии

2023-04-11 04:51 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/ui/ClientListViewTest.kt
> +                node("td") { exists() }
[Это](https://github.com/d-r-q/QYoga/pull/22#discussion_r1156697680) ещё актуально

2023-04-11 05:59 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/WebSecurityConfig.kt
> +            .defaultSuccessUrl("/clients")
сработало

2023-04-12 02:48 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/ClientConfig.kt
> +@ComponentScan("nsu.fit.qyoga.core.clients")
Так я вроде вынесла в соответствующие конфиги из основного файла

2023-04-12 03:53 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/ui/ClientListViewTest.kt
> +                node("td") { exists() }
Сделала

2023-04-13 03:41 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/ClientConfig.kt
> +@ComponentScan("nsu.fit.qyoga.core.clients")
Я там писал, что после переноса ComponentScan сюда, в нём не надо будет дублировать пакет

2023-04-15 11:57 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/ClientConfig.kt
> +@ComponentScan("nsu.fit.qyoga.core.clients")
Убрала пакет из ComponentScan

2023-04-17 00:58 UTC, d-r-q requested changes

2023-04-17 00:58 UTC, d-r-q commented on src/main/kotlin/nsu/fit/platform/spring/NamedParameterJdbcOperationsExt.kt
> +    val count = this.queryForObject(
Вот тут ещё подправь, пожалуйста - сначала запросить кол-во и если оно 0 - сразу вернуть пустую страницу без второго запроса

2023-04-17 00:58 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    @GetMapping("/users/login")
Давай отсюда тогда тоже /users/ уберём

2023-04-17 00:58 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        addClientsPageAttributes(model, clients)
Давай это заменим на:
```kotlin
model.addAllAttributes(toModelAttributes(ClientSearchDto(), clients))
```

```kotlin
fun toModelAttributes(clients: Page<ClientDto>, searchDto: ClientSearchDto): Map<String, *> = mapOf(
    "searchDto" to searchDto,
    "clients" to clients,
    "pageNumbers" to 1 .. clients.totalPages
)

```

Код написал в блокноте - это общая идея.

2023-04-17 00:58 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        model: Model
Давай пагинацию сделаем так же: https://github.com/d-r-q/QYoga/blob/qg-19/implementation-api-creation-questionnaires/src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnairesController.kt#L34

2023-04-17 00:58 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        @RequestParam(value = "pageNumber", required = false, defaultValue = "1") pageNumber: Int,
И тут пагинацию поправить

2023-04-17 00:58 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Client.kt
> +data class Client(
Мы же удалили Spring Data JDBC - давай это уберём, если что из истории достанем

2023-04-17 00:58 UTC, d-r-q commented on src/main/resources/db/migration/common/V23031001__clients.sql
> +    last_name         varchar     not null,
Поправь форматирование, пожалуйста

2023-04-17 00:58 UTC, d-r-q commented on src/main/resources/static/styles/styles.css
> +    background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity))
Это же из бутстрапа файл? кажется его не стоит хачить - не думаю, что ты полностью понимаешь последствия этого (я тоже не понимаю).

Зачем этот хак?

2023-04-17 00:58 UTC, d-r-q commented on src/main/resources/templates/auth.html
> +                                            <output id="errorText"
Для этого в бутстрапе есть спец классы: https://github.com/d-r-q/Q6/blob/master/src/main/kotlin/q6/app/anonymous/RegistrationPage.html#L49

2023-04-17 00:58 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +    fun `QYoga should delete clients with delete-button`() {
Тут нет никаких кнопок

2023-04-17 00:58 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +    fun `QYoga should redirect to clients-list when delete can't client`() {
А тут - редиректов

2023-04-21 17:21 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/anonymous/LoginPageController.kt
> +    @GetMapping("/users/login")
убрала

2023-04-21 17:26 UTC, nntrifonova commented on src/main/resources/static/styles/styles.css
> +    background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity))
Если дописывать стили напрямую в html файле (да и вообще где либо еще), то все они игнорироваться из-за этого important в css. Поэтому убрала его, а сам цвет меняла в html

2023-04-21 17:28 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/core/clients/api/Client.kt
> +data class Client(
Удалила

2023-04-21 17:31 UTC, nntrifonova commented on src/main/resources/db/migration/common/V23031001__clients.sql
> +    last_name         varchar     not null,
поправила

2023-04-21 17:35 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +    fun `QYoga should delete clients with delete-button`() {
переименовала

2023-04-21 17:35 UTC, nntrifonova commented on src/test/kotlin/nsu/fit/qyoga/cases/core/clients/internal/ClientsServiceTests.kt
> +    fun `QYoga should redirect to clients-list when delete can't client`() {
переименовала

2023-04-25 14:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/platform/spring/NamedParameterJdbcOperationsExt.kt
> +    val count = this.queryForObject(
поправила

2023-04-25 14:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        addClientsPageAttributes(model, clients)
добавила

2023-04-25 14:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        model: Model
Поменяла

2023-04-25 14:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        @RequestParam(value = "pageNumber", required = false, defaultValue = "1") pageNumber: Int,
Поменяла

2023-04-25 15:55 UTC, nntrifonova commented on src/main/resources/templates/auth.html
> +                                            <output id="errorText"
испарвила

2023-04-26 02:14 UTC, d-r-q commented on src/main/kotlin/nsu/fit/platform/spring/NamedParameterJdbcOperationsExt.kt
> +    val count = this.queryForObject(
тут весь смысл в том, чтобы не делать второй запрос за данными, если мы уже получили счётчик 0. Их надо местами поменять

2023-04-26 02:17 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        addClientsPageAttributes(model, clients)
Про 1 .. - я не шутил. Так и надо написать: "pageNumbers" to (1 .. clients.totalPages).toList() - это валидный код. можешь даже попробовать убрать ).toList() - так может тоже сработает

2023-04-26 02:27 UTC, d-r-q commented on src/main/resources/static/styles/styles.css
> +    background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity))
И тем не менее. Хачить бутстрап не надо. сделай так и будет тебе щасте:
```html
    <body class="login-body">
        <style>
            .login-body{
                --bs-bg-opacity: 1;
                background-color: #bacbe6;
            }
        </style>
```

2023-04-29 08:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/qyoga/app/therapist/ClientListPageController.kt
> +        addClientsPageAttributes(model, clients)
исправила

2023-04-29 08:31 UTC, nntrifonova commented on src/main/kotlin/nsu/fit/platform/spring/NamedParameterJdbcOperationsExt.kt
> +    val count = this.queryForObject(
поменяла

2023-04-29 08:31 UTC, nntrifonova commented on src/main/resources/static/styles/styles.css
> +    background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity))
сделала

2023-04-29 08:35 UTC, d-r-q approved these changes

2023-04-29 08:38 UTC, merged