Qg 28/implementation images
d-r-q/QYoga pull request #30
Opened 2023-05-03 08:46 UTC by Zertalian1

## Чеклист

* Пулл-реквест
  * [ ] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [ ] Я убедился, что все проверки пршли успешно
  * [ ] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [ ] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [ ] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [ ] Я видел, как каждый тест превратился из красного в зелёный

2023-05-03 09:48 UTC, d-r-q requested changes

2023-05-03 09:48 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/api/ImageService.kt
> +    fun uploadImage(file: MultipartFile): Long
В сервисы нельзя тащить зависимость на веб - давай сюда какой-нить кастомный классик с нужными данными передавать

2023-05-03 09:48 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/internal/ImageJdbcTemplateRepo.kt
> +              values ${idListToValues(idList)}
Надеюсь тут не IN потому что, ты хочешь проверить что всё найдено, а не потому что не знаешь про него.

Но в любом случае - давай без этого. Так обычно не делают, клиент сам в состоянии понять, что ему вернулось не всё, и ему это может быть вполне ок. А так ты ему фигу возвращаешь

2023-05-03 09:48 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/internal/ImageJdbcTemplateRepo.kt
> +class ImageJdbcTemplateRepo(
Подозреваю, ты тут не осилил bytea замапить средствами Spring Data JDBC? Пока ок, но потом переделаем на SDJ - я где-то так уже делал

2023-05-03 09:48 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/internal/ImageJdbcTemplateRepo.kt
> +        val imageList = mutableListOf<Image>()
Я очень очень не люблю всё мутабельное. К любому var-у или mutable* я сразу же пойду докапываться.
Это надо так сделать:
```kotlin
        val imageList = jdbcTemplate.query(query) { rs: ResultSet, _: Int ->
            Image(
                id = rs.getLong("imageId"),
                name = rs.getString("imageName")
                    ?: throw ImageException("No existing image with id = ${rs.getLong("imageId")}"),
                mediaType = rs.getString("imageMediaType"),
                size = rs.getLong("imageSize"),
                data = rs.getBytes("imageData")
            )
        }

```

2023-05-03 09:48 UTC, d-r-q commented on src/main/resources/db/migration/common/V23012301__images.sql
> +    name       VARCHAR,
Надо NOT NULL везде развешать

2023-05-03 09:48 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/api/ImageService.kt
> +    fun getImage(id: Long): Image
Давай тут Image? возвращать из тех же соображений - клиенту в Котлине проще из налла исключение выбросить, чем исключение заигнорить

2023-05-03 10:46 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/images/internal/ImageJdbcTemplateRepo.kt
> +              values ${idListToValues(idList)}
эта функция была написана исключительно для этого кейса
https://github.com/d-r-q/QYoga/pull/27#discussion_r1182045023

2023-05-03 11:25 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/internal/ImageJdbcTemplateRepo.kt
> +              values ${idListToValues(idList)}
ммм, ну кейс выбрать по списку идов - полезный, давай его оставим. Но упростим и АПИ по удобнее сделаем

2023-05-03 12:41 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/images/api/ImageService.kt
> +    fun uploadImage(file: MultipartFile): Long
Заменил на Image

2023-05-03 12:41 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/images/internal/ImageJdbcTemplateRepo.kt
> +class ImageJdbcTemplateRepo(
ну я, вроде, сделал

2023-05-04 02:19 UTC, d-r-q requested changes

2023-05-04 02:19 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/internal/ImageJdbcTemplateRepo.kt
> +        return if (imageList.isEmpty()) null else imageList[0]
Это надо заменить на imageList.firstOrNull()

2023-05-04 02:19 UTC, d-r-q commented on src/main/resources/db/migration/common/V23012301__images.sql
> +CREATE TABLE images
Давай ещё от греха подальше файлу версию сегодняшним днём проставим. А то, боюсь, на qyoga.pro flyway начнёт возмущаться

2023-05-04 02:19 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/images/api/ImageService.kt
> +    fun getImage(id: Long): Image
Это ещё осталось - ты в delete добавил

2023-05-05 03:03 UTC, d-r-q approved these changes

2023-05-05 03:08 UTC, merged