Qg 25/implementation api watch questionnaire results
d-r-q/QYoga pull request #50
Opened 2023-05-25 06:57 UTC by Zertalian1

## Чеклист

* Пулл-реквест
  * [ ] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [ ] Я убедился, что все проверки пршли успешно
  * [ ] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [ ] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [ ] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [ ] Я видел, как каждый тест превратился из красного в зелёный

2023-05-30 03:32 UTC, d-r-q requested changes

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/completingQuestionnaires/CompletingQuestionnairesController.kt
> +        return httpSession.getAttribute("therapistId") as Long?
Зачем тебе ид в сессии? У тебя уже для этого есть принципал. См создание упражнения

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/completingQuestionnaires/CompletingQuestionnairesController.kt
> +                val userId = userService.findByUsername(username)!!.id
Ну и так к слову - а если юзер не найдётся?

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/dtos/CompletingClientDto.kt
> +    var id: Long = 0,
Т ут у тебя вроде нет проблем с маппингом входящей дто - всё val

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/dtos/CompletingDto.kt
> +    var id: Long,
Т ут у тебя вроде нет проблем с маппингом входящей дто - всё val

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/dtos/CompletingQuestionnaireDto.kt
> +    var id: Long = 0,
Т ут у тебя вроде нет проблем с маппингом входящей дто - всё val

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/dtos/CompletingSearchDto.kt
> +    val clientName: String = "",
Т ут у тебя вроде нет проблем с маппингом входящей дто - всё val

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/errors/CompletingException.kt
> +class CompletingException(message: String) : ResourceNotFound(message)
Тут можно сразу кидать ResourceNotFound

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/internal/repository/CompletingJdbcTemplateRepo.kt
> +        val completingList: MutableList<CompletingDto> = mutableListOf()
Никогда-никогда-никогда в этом проекте не используй MutableList. Если не знаешь как обойтись без него - приходи. В данном случае, тебе его вроде можно ваще выкинуть и вернуть результат вызова query

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/internal/repository/CompletingJdbcTemplateRepo.kt
> +            if (completingId == 0L) {
Как такое возможно?

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/internal/repository/CompletingJdbcTemplateRepo.kt
> +            ORDER BY completingDate ${if (type == "UNSORTED") "ASC" else type}
У тебя тут вроде дыра на sql-инъекцию - надо проверять type на множество допустимых значений

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/internal/repository/CompletingJdbcTemplateRepo.kt
> +    fun getRecordsNum(
Для таких штук у нас в платформе уже есть:
fun <T : Any> NamedParameterJdbcOperations.queryForPage(
    baseSql: String,
    filterParams: Map<String, Any?>,
    pageRequest: Pageable,
    rowMapper: RowMapper<T>
): PageImpl<T>

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/internal/serviceImpl/CompletingServiceImpl.kt
> +    @Autowired val completingJdbcTemplateRepo: CompletingJdbcTemplateRepo
Autowired можно и нужно не писать

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/AnswerBoundsDto.kt
>      var upperBound: Int? = null,
Тут точно нужны вары?

2023-05-30 03:32 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/AnswerBoundsDto.kt
>      var upperBound: Int? = null,
Зачем тут Serializable? O_o

2023-05-30 03:32 UTC, d-r-q commented on src/main/resources/db/migration/common/V23052001__comleting.sql
> +    completing_date  date,
Уточни у Марины, достаточно ли ей только даты. Или нужно ещё время. Если нужно - надо заменить на TIMESTAMP

2023-05-30 03:32 UTC, d-r-q commented on src/main/resources/db/migration/common/V23052001__comleting.sql
> +    numeric_result   SERIAL,
Эм? Почему сериал?

2023-05-30 03:32 UTC, d-r-q commented on src/main/resources/db/migration/common/V23052001__comleting.sql
> +)
ON DELETE CASCADE можно вешать только внутри агрегата. Это, кажется, отдельный агрегат. Да и удалять врятли будем - в общем убери на всякий случай

2023-05-30 03:32 UTC, d-r-q commented on src/main/resources/templates/completingQuestionnaires/questionnaire-page.html
> +<script crossorigin="anonymous"
Это уже есть в футере. Два остальных импорта надо выкинуть, если не нужны тебе, либо в футер утащить

2023-05-30 03:32 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +    fun `QYoga returns part of page completing-list then user change sort type`() {
then -> when?

2023-05-30 03:32 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +    fun `QYoga returns similar completing-list on second request`() {
Чёт не понимаю нафига этот тест?

2023-05-30 03:32 UTC, d-r-q commented on src/main/resources/templates/completingQuestionnaires/questionnaire-page.html
> +                                                th:classappend="${!(results.getPageable().pageNumber < results.totalPages - 1) ? 'disabled' : ''}">
Кажись getPageable().pageNumber не работает с пустыми страницами. Напиши плз тест на это. Если сломается - см мой недваний пример на фикс этой проблемы в упражнениях

2023-05-30 03:32 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +    fun `QYoga returns part of page completing-list then user change title`() {
Если это тест на поиск - надо ещё проверить, что контент соответствует фильтру. И в остальных тестах тоже

2023-05-30 08:12 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/AnswerBoundsDto.kt
>      var upperBound: Int? = null,
тут прикол в том, что этот объект является частью CreateAnswerDto, там все вары тк ответ находятся в списке у вопроса => CreateAnswerDto создаётся с полями по умолчанию => AnswerBoundsDto создаётся с полями по умолчанию => нужны var. Теоретически можно сделать поле границ в AnswerBoundsDto nullable, но я не знаю, как на это отреагирует spring data JDBC

2023-05-30 08:19 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/AnswerBoundsDto.kt
>      var upperBound: Int? = null,
а, это остатки спринговой сессии, теперь без этого работает, уберу

2023-06-04 08:46 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/app/completingQuestionnaires/CompletingQuestionnairesController.kt
> +        return httpSession.getAttribute("therapistId") as Long?
ну это я вырезал, сделал получения из принципала

2023-06-04 08:47 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/app/completingQuestionnaires/CompletingQuestionnairesController.kt
> +                val userId = userService.findByUsername(username)!!.id
ну это я вырезал

2023-06-04 08:47 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/dtos/CompletingClientDto.kt
> +    var id: Long = 0,
да

2023-06-04 08:48 UTC, Zertalian1 commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +    fun `QYoga returns similar completing-list on second request`() {
да, там же я в сессию зачем-то id терапевта засовывал, поэтому нужно было сделать тест, который проверял, что в сессии норм id лежит. Но этот бред я вырезал, как и этот тест собсвенно

2023-06-04 08:49 UTC, Zertalian1 commented on src/main/resources/templates/completingQuestionnaires/questionnaire-page.html
> +                                                th:classappend="${!(results.getPageable().pageNumber < results.totalPages - 1) ? 'disabled' : ''}">
написал тест, все работает

2023-06-04 08:50 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/errors/CompletingException.kt
> +class CompletingException(message: String) : ResourceNotFound(message)
этого больше не существует

2023-06-04 08:52 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/internal/repository/CompletingJdbcTemplateRepo.kt
> +    fun getRecordsNum(
переделал

2023-06-04 08:53 UTC, Zertalian1 commented on src/main/resources/db/migration/common/V23052001__comleting.sql
> +    completing_date  date,
только даты

2023-06-05 03:51 UTC, d-r-q requested changes

2023-06-05 03:51 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/internal/repository/CompletingJdbcTemplateRepo.kt
> +        if (pageableSortType != "ASC" && pageableSortType != "DESC") {
Ммм. Так я в прошлый раз чутка затупил. У тебя тут Stringly-typed программа выходит. Как правило это плохо. В данном случае - точно.

Из педагогических соображений - этот код надо было делать через стандартную функцию require и вытаскивать его в контроллер - синтаксическая валидация входных данных выполяется в контроллере.

Но, ещё лучше - исключить недопустимые значения на уровне типов. Что у тебя в целом уже есть, но ты не осилил этим воспользоваться.

Для этого надо:

```kotlin
// Куда-нить в платформу в PageableExt (может уже есть):
private fun Pageable.primarySortDirection() =
    sort.map { it.direction }.firstOrNull()

val sortDirection = pageable.primarySortDirection() ?: Direction.ASC

fun getQueryBySortType(sortDirection: Direction): String {
// ...
    ORDER BY completingDate ${sortDirection.name}
}


```

2023-06-05 03:51 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +                    containsText("13-05-2023")
Тут ты не проверяешь порядок. В целом это, пожалуй, лучше было сделать тестом сервиса. Но можешь так оставить

2023-06-05 03:51 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +                    containsText("02-05-2023")
Тут надо проверять на то, что все строки содержат test

2023-06-05 03:51 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +                    containsText("06-05-2023")
Имя клиента

2023-06-05 03:51 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +    fun `QYoga returns part of page completing-list when user change page`() {
Этот тест чёт не очень понимаю.
Если это тест на пагинацию, то в идеале тут должно быть написано:
Дано:
6 прохождений опросов
размер страницы равен 5
сортировка по убыванию даты прохождения

Когда
мы запрашиваем вторую старница

Тогда
Она содержит одну строку и дата прохождения этой страницы является минимальной из всех дат в исходных данных

2023-06-05 03:51 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/QYogaApplication.kt
> +    CompletingQuestionnairesConfig::class
Отсортируй их по алфавиту, пожалуйста, и добавь соотв. коммент

2023-06-05 03:51 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/dtos/CompletingDto.kt
> +    val completingDate: Date,
LocalDate

Date - устаревшее, неудобное и мутабельное АПИ

2023-06-05 03:51 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/completingQuestionnaires/api/model/Completing.kt
> +    val completingDate: Date,
LocalDate

2023-06-06 09:21 UTC, Zertalian1 commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +                    containsText("13-05-2023")
в сервисе есть тест, который проверяет, чтобы прохождения шли по порядку

2023-06-06 10:33 UTC, Zertalian1 commented on src/test/kotlin/nsu/fit/qyoga/cases/core/completingQuestionnaires/ui/CompletingListViewTest.kt
> +    fun `QYoga returns part of page completing-list when user change page`() {
ну я написал человеческие имена, всё это уместить не получилось, но я пытался

2023-06-07 04:00 UTC, d-r-q approved these changes

2023-06-07 04:00 UTC, merged