Qg 54/generate link modal window
d-r-q/QYoga pull request #55
Opened 2023-06-20 05:41 UTC by Zertalian1

## Чеклист

* Пулл-реквест
  * [ ] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [ ] Я убедился, что все проверки пршли успешно
  * [ ] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [ ] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [ ] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [ ] Я видел, как каждый тест превратился из красного в зелёный

2023-06-22 02:38 UTC, d-r-q requested changes

2023-06-22 02:38 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/createQuestionnaires/QuestionnairesAnswersController.kt
> +package nsu.fit.qyoga.app.questionnaires.createQuestionnaires
О вот это похоже код который я вмёржил без ревью. И раз уж ты его потрогал - давай править.

Тут из всех методов надо утащить логику в сервис, чтобы контроллер выглядел примерно так:

```kotlin
    @PostMapping("/edit/question/{questionId}/answer/{answerId}/add-image")
    fun addImageToAnswer(
        @RequestParam("file") file: MultipartFile,
        @PathVariable questionId: Long,
        @PathVariable answerId: Long,
        model: Model
    ): String {
    val questionnaire = getQuestionnaireFromSession()
    val imageId = imageService.uploadImage(
                                    Image(
                                        name = file.name,
                                        mediaType = file.contentType.toString(),
                                        size = file.size,
                                        data = file.bytes
                                    ))
    val updatedQuestionnaire = questionnaire.addImage(questionId, answerId, imageId)
    model.addAll(mapOf(
        "questionIndex" to updatedQuestinary.questionIndex(questionId),
        "answer" to updatedQuestionary.answer(questionId, answerId), // можно даже updatedQuestionary[questionId][answerId]
       "questionId" to questionId
    ))
}
```

2023-06-22 02:38 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/createQuestionnaires/QuestionnairesQuestionController.kt
> +package nsu.fit.qyoga.app.questionnaires.createQuestionnaires
И тут

2023-06-22 02:38 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnaireGenerateLinkController.kt
> +) {
Вот это прям сразу дурно пахнет. Логику, которая на это завязана надо утащить в ядро.
Главное и в идеале единственное назначение контроллера - странслировать http запрос в вызов сервиса, а потом странслировать ответ в html. В идеале вызов сервиса должен быть один, но в целом допустимо, чтобы их было несколько. Но для того чтобы контроллере появился иф, цикл и вызов метода с лямбдой - нужно очень веское основание

2023-06-22 02:38 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnaireGenerateLinkController.kt
> +    fun getGenerateLinkModalWindow(
Давай questionnaireId утащим в параметры запроса, а нас же ресурс - форма

2023-06-22 02:38 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnaireGenerateLinkController.kt
> +    @GetMapping("/generate-link/{questionnaireId}/action")
И тут в параметр.
Плюс урл пусть будет тот же, а роутинг делать на базе заголовка (https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html#mvc-ann-requestmapping-params-and-headers) HX-Request (https://htmx.org/reference/#request_headers),

2023-06-22 02:38 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnaireGenerateLinkController.kt
> +    @GetMapping("/generate-link/{questionnaireId}/{clientId}/generate")
Иды - в параметры, урл оставить /generate-link, метод - пост

2023-06-22 02:38 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnaireGenerateLinkController.kt
> +        model.addAttribute("generatedLink", link)
И всё это в  QuestionnaireCompletionService

2023-06-22 02:38 UTC, d-r-q commented on src/main/resources/templates/questionnaire/generate_link_modal.html
> +          <input aria-describedby="basic-addon2"
Уточни у Марины - кажется один инпут для всех частей будет удобнее

2023-06-22 02:38 UTC, d-r-q commented on src/main/resources/templates/questionnaire/generate_link_modal.html
> +      <div id="tablePagination" style="height: 50px">
Опционально, я сам не знаю как это сделать и возможно ли, но если хочешь поупражняться - можешь попробовать выделить компонент аля PaginatedTable

2023-06-22 02:38 UTC, d-r-q commented on src/main/resources/templates/questionnaire/questionnaire-list.html
> +    <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
Это зачем?

2023-06-22 02:38 UTC, d-r-q commented on src/main/resources/templates/questionnaire/questionnaire-list.html
> +    <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
А оно видимо в модалке используется. Тогда туда и надо утащить.
Но вообще я этой штуки чёт боюсь и не хочется её в проект тащить. Давай это лучше на альпайне сделаем https://w3collective.com/modal-dialog-alpine-js/

2023-06-22 02:38 UTC, d-r-q commented on src/main/resources/application.yaml
> +qyoga:
Надо тогда ещё завести application-prod.yaml с продовыми настройками и подхачить сборку образа, чтобы туда можно было прокинуть профиль, и run-local.sh, чтобы он прокидывал профиль local-dev, build-docker-image.yaml - чтобы прокидывал prod.

Если залипнешь - пиши, сам сделаю

2023-06-22 02:38 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/generateLink/ui/GenerateLinkViewTest.kt
> +    fun hashGenerator(value: String): String {
Ненене, это тавтология. Сейчас пока можно проверить просто на наличие и формат (длину, символы), а потом надо будет проверить, что по этой ссылке открывается опросник, с корректно зашитыми идами

2023-06-24 13:11 UTC, Zertalian1 commented on src/main/resources/templates/questionnaire/generate_link_modal.html
> +          <input aria-describedby="basic-addon2"
сделал так тк была готовая дтошка и сервис, ок спрошу

2023-06-24 13:16 UTC, Zertalian1 commented on src/main/resources/templates/questionnaire/generate_link_modal.html
> +      <div id="tablePagination" style="height: 50px">
не совсем понял, что имели ввиду, обернуть Page<QuestionnaireDto> во что-то?

2023-06-26 14:26 UTC, Zertalian1 commented on src/main/resources/templates/questionnaire/questionnaire-list.html
> +    <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
это оказалось не совсем то, мне всё же нужно генерить модалку снова тк нужно тягать инфу про клиентов, переделал на чистый js

2023-06-27 11:42 UTC, Zertalian1 commented on src/main/resources/application.yaml
> +qyoga:
ну я вроде сделал, если будете править, то напишите пж, я хоть увижу как правильно

2023-06-28 02:55 UTC, d-r-q requested changes

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/CreateQuestionnaireDto.kt
> +    this.question.filter { it.id == questionId }.getOrNull(0)
Я так понимаю тут проще, быстрее и идиоматичнее использовать firstOrNull

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/CreateQuestionnaireDto.kt
> +    return question.answers.filter { it.id == answerId }.getOrNull(0)
Я так понимаю тут проще, быстрее и идиоматичнее использовать firstOrNull

2023-06-28 02:55 UTC, d-r-q commented on .github/workflows/build-docker-image.yaml
> +        run: ./gradlew build -x check -Dspring.profiles.active=prod
Тут ты прокидываешь пропертю в грэдл - это надо убрать

2023-06-28 02:55 UTC, d-r-q commented on deploy/qyoga/docker-compose-dev.yml
> +      - SPRING_PROFILES_ACTIVE=prod
А вот эта штука, похоже, может сработать, но ты её положив в докер файл для дева, а не прода - надо в соседний файл перевести.
Ну и хорошо бы проверить, что она реально прокинулась

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnaireGenerateLinkController.kt
> +    @GetMapping("/generate-link", params = ["action=true"])
Почему не получилось на заголовках сделать?

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/extensions/CreateQuestionnaireDtoAnswerExt.kt
> +    var isFound = false
У тебя тут куча волосатого дублирования. Надо как минимум его убрать примерно так:

```kotlin

fun CreateQuestionnaireDto.addAnswerImage(
        questionId: Long,
        answerId: Long,
        imageId: Long
): CreateQuestionnaireDto? {
    modifyAnswer(questionId, answerId) {
        it.copy(imageId = imageId)
    }
}

fun modifyAnswer(questionId: String, answerId: String, body: (Answer) -> Answer) = ...
```

Кроме того, если что-то не удаётся найти - надо NoSuchElement или что-то в таком духе выкидывать.

Наконец, если хочешь, можешь попробовать эту либульку прикрутиь: https://github.com/kopykat-kt/kopykat

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/extensions/CreateQuestionnaireDtoQuestionExt.kt
> +fun CreateQuestionnaireDto.addQuestionImage(
Ну и тут аналогично дублирование надо убрать.
Наверное, modifyAnswer можно будет выразить в терминах modifyQuestion

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/GenerateLinkSearchClientsDto.kt
> +fun GenerateLinkSearchClientsDto.toClientSearchDto(): ClientSearchDto {
Это не то, что я и Марина имели ввиду - надо одно поле, которое матчит все три части через или. То есть пишешь ив, и получаешь и Иванов, Ивановичей и Ивановых.

Но я понял, почему ты так сделал - если не хочешь править клиентов - оставляй так, я сам с оказией подхачу.

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/serviceImpl/QuestionnaireCompletionServiceImpl.kt
> +package nsu.fit.qyoga.core.questionnaires.internal.serviceImpl
А зачем тут ещё и serviceImpl?

2023-06-28 02:55 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/HashGenerator.kt
> +import org.postgresql.shaded.com.ongres.scram.common.bouncycastle.pbkdf2.HMac
ммм, чёт я прошляпил, что ты hmac из постгреса взял. Давай лучше джавовый возьмём: https://www.baeldung.com/java-hmac#hmac-using-jdk-apis

2023-06-28 02:55 UTC, d-r-q commented on src/main/resources/templates/questionnaire/generate_link_modal.html
> +      <div id="tablePagination" style="height: 50px">
Нет, превратить этот кусок хтмля во фрагмент, который можно на всех страницах использовать.

2023-06-28 02:55 UTC, d-r-q commented on src/main/resources/application.yaml
> +qyoga:
Да, вроде ок, деплой покажет:)

2023-06-28 02:55 UTC, d-r-q commented on src/main/resources/templates/questionnaire/questionnaire-list.html
> +    <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
ммм, ну ты подикась мог заюзать htmx внутри модалки внутри alpinejs внутри htmx :troll:
Ладно, пусть так будет

2023-06-28 02:55 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/ui/QuestionnaireImageViewTest.kt
> +            contentType(ContentType.MULTIPART)
ооооо-хо-хо...

Я щяс после ревью пойду писать о том почему гет-методы важно делать безопасными. Это всё надо на посты/путы переделать.

Плюс у тебя тут кейсы перемешаны - addAnswer и add-question.

Это всё не про тест, конечно.

А вот про тест - все эти методы - это фикстура теста (Given). В идеале для них надо запилить отдельный класс QYogaClient, чтобы тут в When остался только запрос, который реально тестим. Но это опционально - если не хочешь, можешь не делать

2023-06-28 02:55 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/ui/QuestionnaireImageViewTest.kt
> +            get("/therapist/questionnaires/new")
Ну и если это всё вынести в клиента, то можно будет дслчик запилить аля:
```kotlin
qyogaClient.createSingleAnswerQuestionarieDraft()
```

2023-06-28 04:14 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/app/questionnaires/QuestionnaireGenerateLinkController.kt
> +    @GetMapping("/generate-link", params = ["action=true"])
не то слово поставил, сделал на заголовках

2023-06-28 04:24 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/ui/QuestionnaireImageViewTest.kt
> +            contentType(ContentType.MULTIPART)
Вот этот пост: https://azhidkov.pro/microposts/23/06/rest-fronts-and-others/

2023-06-29 05:50 UTC, Zertalian1 commented on deploy/qyoga/docker-compose-dev.yml
> +      - SPRING_PROFILES_ACTIVE=prod
![image](https://github.com/d-r-q/QYoga/assets/91644941/8ca05dc1-0838-4c57-90d5-97030d98303d)
ну, как я вижу, профиль встал, но, наверное, вам тоже стоит попытаться проверить, ибо я тестирую в wsl

2023-06-29 06:00 UTC, Zertalian1 commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/ui/QuestionnaireImageViewTest.kt
> +            contentType(ContentType.MULTIPART)
методы поменял, исправил тесты, там было много лишнего

2023-06-29 14:19 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/GenerateLinkSearchClientsDto.kt
> +fun GenerateLinkSearchClientsDto.toClientSearchDto(): ClientSearchDto {
я добавил функцию поиска

2023-06-29 16:01 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/GenerateLinkSearchClientsDto.kt
> +fun GenerateLinkSearchClientsDto.toClientSearchDto(): ClientSearchDto {
старую пока не трогал и ничего не менял на странице, ели это делать, то точно не в этом пр, тут уже и так дофига

2023-06-30 03:20 UTC, d-r-q commented on deploy/qyoga/docker-compose-dev.yml
> +      - SPRING_PROFILES_ACTIVE=prod
На проде проверим :trollface:

2023-06-30 03:26 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/extensions/CreateQuestionnaireDtoAnswerExt.kt
> +    imageService: ImageService
Это очень плохая затея. Ты чистую функцию превратил в грязную. А ещё у тебя изображение создаётся на одном уровне, а удялется на другом.

Вообще - яп забил на обработку этой ошибки и не удалял бы изображение, в случае если ответ не найден. Но если очень хочешь удалять - верни это на уровень создания

2023-06-30 03:27 UTC, d-r-q commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/extensions/CreateQuestionnaireDtoAnswerExt.kt
> +            }.toMutableList()
Кажется, это можно засунуть внутрь modifyAnswer

2023-06-30 03:34 UTC, d-r-q commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/ui/QuestionnaireImageViewTest.kt
> +            contentType(ContentType.MULTIPART)
У тебя небезопасный /therapist/questionnaires/new остался гетом. И editQuestionnaire. И addResultToQuestionnaire

2023-06-30 05:48 UTC, Zertalian1 commented on src/test/kotlin/nsu/fit/qyoga/cases/core/questionnaires/ui/QuestionnaireImageViewTest.kt
> +            contentType(ContentType.MULTIPART)
ыыыыыы, поправил

2023-06-30 05:49 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/HashGenerator.kt
> +import org.postgresql.shaded.com.ongres.scram.common.bouncycastle.pbkdf2.HMac
это я сделал же...

2023-06-30 05:49 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/internal/serviceImpl/QuestionnaireCompletionServiceImpl.kt
> +package nsu.fit.qyoga.core.questionnaires.internal.serviceImpl
убрал

2023-06-30 06:20 UTC, Zertalian1 commented on src/main/kotlin/nsu/fit/qyoga/core/questionnaires/api/dtos/extensions/CreateQuestionnaireDtoAnswerExt.kt
> +    imageService: ImageService
ну я и забил)

2023-06-30 06:23 UTC, Zertalian1 commented on deploy/qyoga/docker-compose-dev.yml
> +      - SPRING_PROFILES_ACTIVE=prod
![image](https://github.com/d-r-q/QYoga/assets/91644941/a14c15be-fc53-4b2b-8a83-aaf2b7ccf83e)

2023-07-06 01:34 UTC, d-r-q approved these changes

2023-07-06 01:34 UTC, merged