Тест вёрстки и Реализация эндпоинта сохранения
d-r-q/QYoga pull request #86
Opened 2023-11-17 15:28 UTC by MacsiaProduction

## Чеклист

* Пулл-реквест
  * [ ] Я проверил, что в ПРе нет лишних коммитов и мёржей
  * [ ] Я убедился, что все проверки пршли успешно
  * [ ] Я сделал анонс в Telegram-канале QYoga
* Дизайн
  * [ ] Я проверил, что модули (классы сервисов) зависят не более чем от трёх других модулей
  * [ ] Я разделил ввод-вывод, вычисления и оркестрацию
* Тестирование
  * [ ] Я видел, как каждый тест превратился из красного в зелёный

2023-11-18 02:18 UTC, d-r-q requested changes

2023-11-18 02:18 UTC, d-r-q commented on src/test/kotlin/pro/qyoga/clients/pages/therapist/clients/CreateClientPage.kt
> +        val birthDate = text("birthDate") //?)
У тебя код проверку детектом не проходит

2023-11-18 02:18 UTC, d-r-q commented on src/test/kotlin/pro/qyoga/clients/api/TherapistClientsApi.kt
> +            get(CreateClientPage.path)
Почему CreateClientPage? Из-за этого половина тестов валится

2023-11-18 02:18 UTC, d-r-q commented on src/test/kotlin/pro/qyoga/clients/pages/therapist/clients/CreateClientPage.kt
> +    override val title = "Создать клиента"
Новый клиент, см. упражнения

2023-11-18 02:18 UTC, d-r-q commented on src/test/kotlin/pro/qyoga/clients/pages/therapist/clients/CreateClientPage.kt
> +        val birthDate = text("birthDate") //?)
Что значит //?)

2023-11-18 02:18 UTC, d-r-q commented on src/test/kotlin/pro/qyoga/cases/app/therapist/clients/CreateClientTest.kt
> +        val newClientRequest = CreateClientRequest(
Это надо делать через ObjectMother.

см [Тесты не должны использовать продовый код напрямую](https://azhidkov.pro/ergo-approach/guideline/test-automation/#_%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%BD%D0%B5_%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C_%D0%BF%D1%80%D0%BE%D0%B4%D0%BE%D0%B2%D1%8B%D0%B9_%D0%BA%D0%BE%D0%B4_%D0%BD%D0%B0%D0%BF%D1%80%D1%8F%D0%BC%D1%83%D1%8E)

2023-11-18 02:18 UTC, d-r-q commented on src/test/kotlin/pro/qyoga/cases/app/therapist/clients/CreateClientTest.kt
> +        val newClient = ClientDtoObjectMother.createClientDto(
и тут в ОМ передавать newClientRequest

2023-11-19 15:48 UTC, MacsiaProduction commented on src/test/kotlin/pro/qyoga/clients/pages/therapist/clients/CreateClientPage.kt
> +        val birthDate = text("birthDate") //?)
Других форматов я не нашел, но идейно это не совсем строка текста

2023-11-19 16:54 UTC, MacsiaProduction commented on src/test/kotlin/pro/qyoga/clients/pages/therapist/clients/CreateClientPage.kt
> +        val birthDate = text("birthDate") //?)
У меня он почему-то не работает

2023-11-20 05:11 UTC, d-r-q commented on src/test/kotlin/pro/qyoga/clients/pages/therapist/clients/CreateClientPage.kt
> +        val birthDate = text("birthDate") //?)
"он почему-то не работает" - в ответ на это я могу предложить только "надо его как-то починить".

Если хочешь конкретной помощи - точно формулируй свои проблемы, прикладывай логи и скрины, пиши шаги как проблему повторить

2023-12-04 03:58 UTC, closed without merging